language: python
addons:
  apt:
    packages:
    - zlib1g-dev
    - libncurses5-dev
    - libncursesw5-dev
    - libbz2-dev
    - liblzma-dev
cache:
  directories:
  - build
  - "$HOME/.cache/pip"
before_deploy: source ./install_dependencies.sh
deploy:
  provider: pypi
  user: sanger-pathogens
  password:
    secure: hy9+ivWNCXXNcFdIecHhvMI4Ykff5Ykmkpx3vTOqJmbJ7y5gUfTo3QVbDV1PFQedTDT9xb1hmfMuDO/zhSr2EhGdGepPG76a0Zogt8QjV4FaaCkFJefemJ54ybU6j4zt1mMdgZJToP9hSZ3uZ2Y3zyy5Nlw+3nrsrNhqQ6bcm08=
  on:
    tags: true
arch:
  - amd64
  - ppc64le
python:
- '3.5'
- '3.6'
env:
- SAMTOOLS_VERSION=1.3.1
- SAMTOOLS_VERSION=1.4.1
- SAMTOOLS_VERSION=1.5
- SAMTOOLS_VERSION=1.6
sudo: false
install:
- source ./install_dependencies.sh
before_script:
  - pip install codecov
script:
  - "coverage run setup.py test"
after_success:
  - codecov
